# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77b9fa868079eeb8adf9fa077d7a6d7f2b29a827407c03ecfae8448f2a81259ede2ef26810c45b4486245ab90fe4ffc41488804cbeaa6e9259330c1889d7f205

test:
  secret_key_base: 84341e43a5aaf1380170476faf92028d991cc83f86850c08ed3a33bafd534ff757d4ad54ea9414e36fb9937e7a52e8d3dc1de19affb3c0a748b9e74413ee1e68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
